import "./global.scss";
import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Widgets – Reyes",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <div className="rootLayout">
          <p className="topBanner">Show-off Project 🚀</p>
          <div>{children}</div>
        </div>
      </body>
    </html>
  );
}
